# Generated by Django 3.2.16 on 2024-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Название ингредиента'),
        ),
    ]
